import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/providers/theme-provider"
import { Toaster } from "@/components/ui/sonner"
import { auth } from "@/auth"
import { SessionProvider } from "next-auth/react"
import { MainHeader } from "@/components/main-header"
import { usePathname } from "next/navigation"
import { headers } from "next/headers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <MainHeader />
          {children}
          <Toaster />
        </body>
      </html>
    </SessionProvider>
  )
}
