export const players = {
  top: [
    {
      id: 1,
      nickname: "Doran",
      name: "최현준",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfODAg/MDAxNzA1NDU2OTQyMTA1.gHtdN2kDQX2rKWOhNo7YnUBLx_u_vTEMT-zkyqenJ64g.6UfIVG5OWuZyA0IBWQkf8DmyGdy9LFNM4M6rHi2p-qwg.PNG/ymzlJGIJoYqKBwvFlRtF.png",
      career: [
        "2019 LCK Summer 준우승",
        "2020 LCK Summer 준우승",
        "2022 LCK Spring 준우승",
        "2022 LCK Summer 우승",
        "2023 LCK Spring 우승",
        "2023 LCK Summer 우승",
      ],
    },
    {
      id: 2,
      nickname: "Zeus",
      name: "최우제",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfMjQ0/MDAxNzA1NDU3NDIzNzI1.H7a-eGKJW4ks99vCEmgGD9u5GkwpKf7o8JB0m0ZqPlkg.NaL0Lrz5M5Mqtlmw1WNOeWxfN26-21acU_VzYDDKdJUg.PNG/qChUbfgcgfVstXnTBegZ.png",
      career: [
        "2021 LCK Summer 준우승",
        "2022 LCK Spring 우승",
        "2022 MSI 준우승",
        "2022 LCK Summer 준우승",
        "2022 Worlds 준우승",
        "2023 LCK Spring 준우승",
        "2023 LCK Summer 준우승",
        "2022 항저우 아시안 게임 금메달",
        "2023 Worlds 우승",
      ],
    },
    {
      id: 3,
      nickname: "Burdol",
      name: "노태윤",
      img: "https://nng-phinf.pstatic.net/MjAyMzEyMTVfOTcg/MDAxNzAyNjUxMTAxMzkw.vAdl4pQliWbHYBsblGQ6Ja-puuyZh1kH13gJmGucIykg.MXF1KBUEs0wFpUJ8XxQwLFm4NrZF7hSDCzbcgxhcT1wg.PNG/JQvNMhCaLDTPfMHUkGkr.png",
      career: ["2021 LCK Spring 준우승"],
    },
    {
      id: 4,
      name: "김창동",
      nickname: "Canna",
      img: "https://nng-phinf.pstatic.net/MjAyMzExMjFfMjg5/MDAxNzAwNTI3NTg0MjIz.1rMK8n54kYUrG_PvS2NVx0tZIKoHRlATMlH02TvKXpgg.cgAy5NT3CYTGhA9ZKg6rezaRfKh9PKkaS7XXYrCDVE8g.PNG/sRUTNHzTwzSybvDFYjcd.png",
      career: ["2020 LCK Spring 우승", "2021 LCK Summer 준우승"],
    },
    {
      id: 5,
      nickname: "Kiin",
      name: "김기인",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfMjQg/MDAxNzA1NDcwNjIzNDU4.XtyuZGTr0mGcoPJclSGt_b897xlK0Kj7qaX4DjGSGVQg.Z8Gk1Wdlk16YWpCnoUVsEdb-WPVW7Uej2zYwh7QvHC4g.PNG/JGDiuPBQuBwpJPlxIIWM.png",
      career: [
        "2018 LCK Spring 준우승",
        "2018 자카르타팔렘방 아시안게임 은메달",
      ],
    },
    {
      id: 6,
      nickname: "Rascal",
      name: "김광희",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfNDgg/MDAxNzA1NDU2MTAxMTA0.H4mhXL-_Hrx8_WpUQbwMVmcpNGsx6yCnmaPuHim2ylAg.Bojoj-0u4MwfDE-hUWNRh_7Abdg8_imZhG8tsr4_HTAg.PNG/eYwyMNiNphbWZPIgolBF.png",
      career: [
        "2017 LCK Summer 우승",
        "2020 LCK Spring 준우승",
        "2021 LCK Spring 준우승",
      ],
    },
    {
      id: 7,
      nickname: "DuDu",
      name: "이동주",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfMTg4/MDAxNzA1NDU2OTQzMDgy.q_jlQO9hpM0osiltqHn2vLG86wJW5q4bpfI0il8M0mIg.nR57jxwuivQ8PPcQYSwa3V3suEMzW3wJLTUKXCWXjzQg.PNG/fxxVaMbEPCDZdjCdKThO.png",
      career: null,
    },
    {
      id: 8,
      nickname: "DnDn",
      name: "박근우",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfNDkg/MDAxNzA1NDU3MzYyMzIw.HS8Og4jfGTesfBCPpc-QeoI-D473cb7ruHrg9Q6pRMIg.pJNHmEvOBQ_UbIl68J5PUnXy_nhpjuUfP76MbXTZEJ0g.PNG/ZQlchMLeoqlpWLIizTIB.png",
      career: null,
    },
    {
      id: 9,
      nickname: "Morgan",
      name: "박루한",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfMTY5/MDAxNzA1NDU0NTQyMTE0.PsgAjT-FwQ-_wnlJbzdCeOUBRgvnJ5TVOeeJSHHcy64g.A-__67NvzoarSywwnUjMqiwfMfcMhmuq_mVK_0cszPEg.PNG/olOpmUixhnRkJmrRqmkz.png",
      career: null,
    },
    {
      id: 10,
      nickname: "Kingen",
      name: "황성훈",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfNDEg/MDAxNzA1NDU0NjYxMjgx.wcH6_Qrw85eTps8vLZLe6Ivt7FQozfMAFKqrpdroLccg.Mc7GShXooMp05ZzdjLeI8VxEbsSdJiS4VKXTerFnJIQg.PNG/kOTtMkBlfzmyJPtyHHXX.png",
      career: ["2018 LCK Summer 우승", "2022 Worlds 우승"],
    },
    {
      id: 11,
      nickname: "PerfecT",
      name: "이승민",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfMjI0/MDAxNzA1NDU3MzYyMTMy.rHgHHvpKDm9jP-plKLj1numQv2Aiz3zzUgWonUxYbrog.EcGQjwiei9ClDjv7ePcieFxjrF0DLDNLGbp2PVGWSmcg.PNG/iotMlEzmehSAwyRgVPMW.png",
      career: null,
    },
    {
      id: 12,
      nickname: "Clear",
      name: "송현민",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTlfMTY0/MDAxNzA1NjM4NTAzNDUw.SVD-CpGfPJf8Qp_kSlZghoPMaWKraJm37KEJo8oKv9og.CroHtoNluy3N-X7O5sglzoeXZScTZGDqLtqVJhOu2Kcg.PNG/YBtRCoCbGhVAbOLfznVF.png",
      career: null,
    },
    {
      id: 13,
      nickname: "Frog",
      name: "이민회",
      img: "https://nng-phinf.pstatic.net/MjAyNDAzMTZfMTk2/MDAxNzEwNTgyNDQxNjg2.dQB8-PkaBoG84Uu21kmzMHemgxh50-Tt08Vsrm91jdIg.tqZyYf0HlAYR8ATVdCwff2tOhDHVSv2fyiqsqnTHAjUg.PNG/OTgfBKPVdgXIAzaCKgKw.png",
      career: null,
    },
    {
      id: 14,
      nickname: "Dove",
      name: "김재연",
      img: "https://nng-phinf.pstatic.net/MjAyMzEyMDRfMjgz/MDAxNzAxNjU2NDI1MTkz.E6AbQ_bBsssHeQVJYIizHiglN85ITNsJr6fsAErQWw0g.0GeI6T_TOcrT9oSOD9ahKs4Sivef7P3cZIWCYnYBXfgg.PNG/YnZdiXXLXrMRqGdNRwgY.png",
      career: null,
    },
    {
      id: 15,
      nickname: "Sword",
      name: "최성원",
      img: "https://nng-phinf.pstatic.net/MjAyMjExMjFfMTM4/MDAxNjY5MDA0MDU1NzI2.pS0IY8Hxo8mMZYLKo5GG9sEV2x275-qcN5m6mVZ63gMg.Pxn2kfqKF-enQb-tVf8bUxhwO1pnw2UjEnb115BpaSwg.PNG/rUHIhewZDMkUalzOQOzk.png",
      career: [
        "2018 LCK Summer 준우승",
        "2019 LCK Spring 준우승",
        "2019 LCK Summer 준우승",
      ],
    },
    {
      id: 16,
      nickname: "Nuguri",
      name: "장하권",
      img: "https://nng-phinf.pstatic.net/MjAyMjExMTZfMjYz/MDAxNjY4NTc2ODU1MTEy.lAR7THYJyTYuqXAym6q_AqwuJ2jJ9M0VDxCEl7Goz3og.6Su5F3aNmcQUc4yYuB-eFkFPB-CrSqmMaLkM42IHtNEg.PNG/DhQzsimYeHpdRRNzRRWm.png",
      career: [
        "2020 LCK Summer 우승",
        "2020 Worlds 우승",
        "2021 LPL Spring 준우승",
        "2021 LPL Summer 준우승",
      ],
    },
    {
      id: 17,
      nickname: "Zest",
      name: "김동민",
      img: "https://nng-phinf.pstatic.net/MjAyMzExMjFfODgg/MDAxNzAwNTI3NzAxNzQ2.KbyJftTjI7foJ5QT2lO-yTf_OfsVuwVCEhVx8W7miFUg.DocmAvVIyQ-fYh6qx5bLTl4rtZH_WVjGiI0DSjj9sJgg.PNG/yjCzPMvcLFsNTPSYwWsY.png",
      career: null,
    },
    {
      id: 18,
      nickname: "Hoya",
      name: "윤용호",
      img: "https://nng-phinf.pstatic.net/MjAyMzA0MTBfMjgg/MDAxNjgxMDkzNTg0OTYw.R45XCTzC9lvUBlsuEVpwfrR8SEBVBWUWIdj8JjJp3u8g.c1iX2cuNuhyek0H5dZ_BXBgZpj9P0Kz7tP_4uBg2zekg.PNG/VxECRvRgdnjqbbyJfxVT.png",
      career: null,
    },
    {
      id: 19,
      nickname: "Khan",
      name: "김동하",
      img: "https://nng-phinf.pstatic.net/MjAyMTExMTZfMjgg/MDAxNjM3MDIzODcxNzM4.NYkMkxh_QZXVHc-nHlnhDq4bnuuoJB7eNp-351N6vPQg.iLuq54HKXbbrP87r67ZySDvMTodD3c6h8Xr3yAvAbhgg.PNG/tyjiwGbqdJbGWhTcZBxU.png",
      career: [
        "2017 LCK Summer 우승",
        "2018 LCK Spring 우승",
        "2018 MSI 준우승",
        "2019 LCK Spring 우승",
        "2019 LCK Summer 우승",
        "2021 LCK Spring 우승",
        "2021 MSI 준우승",
        "2021 LCK Summer 우승",
        "2021 Worlds 준우승",
      ],
    },
    {
      id: 20,
      nickname: "Rich",
      name: "이재원",
      img: "https://nng-phinf.pstatic.net/MjAyMzA1MDNfMjc2/MDAxNjgzMTI0MDM5NjUy.ps3a_lwrZf1csEDBUYtc5r3-qXRRZqM_hklFrpMNue0g.6ENLxfsDWtg6GQgSF1NzHh5zPYo4X1cHo_cGWObMVUAg.PNG/rqmlnKJhWKTmEfrAWYeH.png",
      career: null,
    },
    {
      id: 21,
      nickname: "Summit",
      name: "박우태",
      img: "https://nng-phinf.pstatic.net/MjAyMzEyMjBfMjYz/MDAxNzAzMDM3MjAxODc3.omXH9CYtUS5q_4gWQhBIGtiIgpwWj8iqgaZT159MaGEg.W46jfe4kUuW5SoxTilBJWpGHXuM6OUlsF-EJ1WwvvFMg.PNG/QPxsjraiiKyvtfXSnGPo.png",
      career: null,
    },
    {
      id: 22,
      nickname: "Destroy",
      name: "윤정민",
      img: "https://nng-phinf.pstatic.net/MjAyMTExMTJfMzQg/MDAxNjM2Njg0MjEyNDgy.nGS1qez7yuS1Oi-C4jj-0tik2ZXN40wQxnxlwNSq71Ug.TzT-8VJlHNk2UH7JSldFnXgILo5HoYlIGTJIa0xpRA8g.PNG/LFMJoTNUJPVCdlEgxrTs.png",
      career: null,
    },
    {
      id: 23,
      nickname: "SoHwan",
      name: "김준영",
      img: "https://nng-phinf.pstatic.net/MjAyMzA0MTdfMTMx/MDAxNjgxNzA3NzQxNDUy.qmL_jF53lxtDWj2AFQfMUHEhavtYhPBWoJcJ2zvSF-og.aUh5R5v3Sef7c2tDWXHncoUTMi74RvxI3EQLFltOyuIg.PNG/MBzEUauUmOfAuUOjbxdf.png",
      career: null,
    },
    {
      id: 24,
      nickname: "Smeb",
      name: "송경호",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfOTkg/MDAxNjE0MTcyNTcxNzg2.tPuX8vV5wQLp8iP1zoxLgh5iyIATnymfxJcTwE1WWr0g.seROV5oEK3NVJiRrE7PsmgZ2voti1-OqYtzGnCujrxYg.PNG/VcJNqBQkNQbPEAQMkgJX.png",
      career: [
        "2015 LCK Spring 준우승",
        "2015 Worlds 준우승",
        "2016 LCK Spring 준우승",
        "2016 LCK Summer 우승",
        "2017 LCK Spring 준우승",
        "2018 LCK Summer 우승",
      ],
    },
    {
      id: 25,
      nickname: "Ikssu",
      name: "전익수",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfMjgg/MDAxNjE0MTcyNTcxMTc4.hpYJaWkQSPZP7820J8ZrMBWbH8B5UsxHCKTDY5o31tsg.b7dnH3DMHmBgI-OlB185ULZqUD2E0wSoRnSF9GCYqDYg.PNG/DsjAApHoXZREEHCCdHqt.png",
      career: null,
    },
    {
      id: 26,
      nickname: "CuVee",
      name: "김동하",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfMTAy/MDAxNjE0MTcyNTcxNDc3.dngvfD0DoczcPFNPXIJWIAunS4HQ7L2SebF11IzQw20g.HetFF1P6PSKW_KNcz28mwaToUPjuCqZE9KXJDtFGHNUg.PNG/pPuOTxCJEKHAuWNLoQDK.png",
      career: null,
    },
    {
      id: 27,
      nickname: "Lonely",
      name: "한규준",
      img: "https://nng-phinf.pstatic.net/MjAyMjA0MTlfMTUg/MDAxNjUwMzI5NTM2NDY3.tLlkYxqXK0z_c6ItJUJlvmSHnOFfuAwKFH0tYAtJTr4g.-D5fFdVkaQ2aOcIXdWPzn5cNQtkD1jUI4VsAyIbTSJEg.PNG/VSgzOKLiZSDZIMQmRGaM.png",
      career: null,
    },
    {
      id: 28,
      nickname: "Untara",
      name: "박의진",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfMTc4/MDAxNjE0MTcyNTcyMjI0.YJDUOpOSgFN07d4La6ryMFR_FvqxQPS3tPPpijFcgVMg.8h_wBEaxfW90iLRsbZUwcSOtMJlvZfeAb6i-jd-qhXIg.PNG/HmHUOQdXwIEXKawgJbfv.png",
      career: ["2017 LCK Summer 준우승"],
    },
    {
      id: 29,
      nickname: "Roach",
      name: "김강희",
      img: "https://nng-phinf.pstatic.net/MjAyNDAyMjFfMjY3/MDAxNzA4NDgyMjYyNzEy.uKun9AOYGXKcguSZ4xTZmOvE8t_DU6SeUeWPaWW0b5Ug.7l0agzX0HM7la8ORFJDCs9Q3FmURzqi4pCxs77Nt7pAg.PNG/oOjuLmffACNVtrmcwnYa.png",
      career: ["2016 LCK Summer 우승", "2020 LCK Spring 우승"],
    },
    {
      id: 30,
      nickname: "Ray",
      name: "전지원",
      img: "https://nng-phinf.pstatic.net/MjAyMjA1MTdfMTAx/MDAxNjUyNzc5MTU1OTU1.KDw9tU6ZxPfcNJpXihvo_uQywQ7EYHsXJnlEoaIMnU8g.7D-Ik8tz4HIAz_6PCVMr-EwDT7wmADE1TiiGMIQjD8Mg.PNG/uEvLRgbIEkjVKmXgKRbr.png",
      career: null,
    },
    {
      id: 31,
      nickname: "Thal",
      name: "박권혁",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfMTQz/MDAxNjE0MTcyNTczNDgz.XZ4C9Ua5JP4RE7HaOuf0qJodzRodiNYqjT82BYBBhNog.YyRORIFf1icKfNNvm6THfI01NWN5JkyrLe1_eM-x4kkg.PNG/lAbEwdsFumEZwTAvDVSi.png",
      career: null,
    },
    {
      id: 32,
      nickname: "Lindarang",
      name: "허만흥",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfMTcw/MDAxNjE0MTcyNTcyNTQ3.KueLNk-ZZ73_5PhKHjzeaO7TWkFpvqaHcOh6DvJtzlEg.ZOuFeGo644sVhrtXqusKl5QkeAlrfqCnBbz49xn8NQIg.PNG/KeXsuDNpfZgrHzCfjMjk.png",
      career: null,
    },
    {
      id: 33,
      nickname: "TaNa",
      name: "이상욱",
      img: "https://nng-phinf.pstatic.net/MjAyMTExMTJfMTc3/MDAxNjM2Njg0MjEyNjEz.yBk5ShGBU-TyorUgCXIqvzieG0cVfMH4b2bjb_y4u_Qg.8O0i7f1X5IHi5qSnoRUwUW_IfbQbqZEXT6YKMKenCMog.PNG/kdDDMypLSgAswnRsmspZ.png",
      career: null,
    },
    {
      id: 34,
      nickname: "Flame",
      name: "이호종",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfNzQg/MDAxNjE0MTcyNTcxMTE2.ynU3H_UurwO50sjXBwPER_zsejiWFynJYPF6OIPuFaog.sNLZTHR6RnopW0Z-3PxSRQOMgUVki6lVhk-ez19LDrgg.PNG/QTOhgaSHKPqmuwTCLTsv.png",
      career: [
        "2013 LCK Spring 준우승",
        "2015 LPL Spring 준우승",
        "2015 LPL Summer 우승",
        "2020 LCK Summer 우승",
      ],
    },
    {
      id: 36,
      nickname: "Wizer",
      name: "최의석",
      img: "https://nng-phinf.pstatic.net/MjAyMjA0MTlfMjc5/MDAxNjUwMzMzMzE2MTQ0.AbOVhJ1HfoKFsuukTqseBHSMAiw9UYEtxyARmb9zypUg.ADuoaQsjqsxniJ2MkVzCP-MSoBxQbEKXwQixhisrNP0g.PNG/uPyLEibsmDaofuxfBDJj.png",
      career: null,
    },
    {
      id: 37,
      nickname: "Crazy",
      name: "김재희",
      img: "https://nng-phinf.pstatic.net/MjAyMjExMThfMTE5/MDAxNjY4NzU0ODE1NjIx.4ZRTw0C-0glsO2e9DHSNyCn7k9Cfg1Om5B845xl2Uxcg.Vzh0fLfAYGztcteNA-FC4p6bQwC9KqY9aCqBNhaJIwAg.PNG/psKsShEPgNuufavfEjIl.png",
      career: ["2019 LCK Spring 우승", "2019 LCK Summer 우승"],
    },
    {
      id: 38,
      nickname: "Alphamong",
      name: "문창민",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfMTIw/MDAxNjE0MTcyNTc2Mzky.bNaeTRB_VeN6MNn6w5beW4X9jUcMrSxFMXVFQh9S_cwg.Mr3AE5CUXo259tVI0OAy3dWnWjtFZOOr3yHEDXIfAbwg.PNG/iEIkDzaKJXryCwRmUbsX.png",
      career: null,
    },
  ],
  jgl: [
    {
      id: 1,
      nickname: "Peanut",
      name: "한왕호",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfNzcg/MDAxNzA1NDU2ODIyNTIw.30BqqebKJzyjG5aYd0ry6_TH4hBeEy9YWiKMy2sYrC0g.N63Ev2dR_xcA9D4rM0F-RBlQ2fBbZ5AJ8mMagG_OCO8g.PNG/tIokjgleZRwJSykQaDwl.png",
      career: [
        "2016 LCK Spring 준우승",
        "2016 LCK Summer 우승",
        "2017 LCK Spring 우승",
        "2017 MSI 우승",
        "2017 LCK Summer 준우승",
        "2017 Worlds 준우승",
        "2018 LCK Spring 우승",
        "2017 MSI 준우승",
        "2018 자카르타 팔렘방 아시안 게임 은메달",
        "2022 LCK Spring 준우승",
        "2022 LCK Summer 우승",
        "2023 LCK Spring 우승",
        "2023 LCK Summer 우승",
      ],
    },
    {
      id: 2,
      nickname: "Oner",
      name: "문현준",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfNjEg/MDAxNzA1NDU3NDIzODk3.UJxW29U-70s8MU11ielpodxabDHgZrQBJ_Y-PCI-uGEg.JE4TTAIfkKVWfoxYVvmszdsDu2xwf-ot29qjSyBWIi0g.PNG/HxGBtzAzRATVqniyadOy.png",
      career: [
        "2021 LCK Summer 준우승",
        "2022 LCK Spring 우승",
        "2022 MSI 준우승",
        "2022 LCK Summer 준우승",
        "2022 Worlds 준우승",
        "2023 LCK Spring 준우승",
        "2023 LCK Summer 준우승",
        "2023 Worlds 우승",
      ],
    },
    {
      id: 3,
      nickname: "Willer",
      name: "김정현",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTlfNSAg/MDAxNzA1NjM4NTAzOTM5.FWyIYc2gFqRxVAj5gOKfVHxD9gRgYwMQi5rvCyvDjr4g.6ZCaTKPuFbKntAvJF9qY4lUFFU_hQ2CdmauB-ZWFA_sg.PNG/ZHSpnyodjIjtbBOVqvoS.png",
      career: null,
    },
    {
      id: 4,
      name: "김건부",
      nickname: "Canyon",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfMjAy/MDAxNzA1NDcwNjIzNzMw.9pbOiMn33RQBB1aY4KFiiawbHxTn0dG8LPYjJpgFLAUg.seTYoqk-4CxPXx0710UxUG1Qp7DTdkI8P-OM3e4Mutcg.PNG/xcXEMNRWAqgcxjkNUYZe.png",
      career: [
        "2020 LCK Summer 우승",
        "2020 Worlds 우승",
        "2021 LCK Spring 우승",
        "2021 MSI 준우승",
        "2021 LCK Summer 우승",
        "2021 Worlds 준우승",
      ],
    },
    {
      id: 5,
      nickname: "Cuzz",
      name: "문우찬",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfMTU0/MDAxNzA1NDU2OTQyOTMx.y17c8aU3p3rkb2eimGz9TcBDYtFNxMxp7BKaQUcUw-4g.cxJ0ppzIod1PVZHRL-p1kw43Ohslnvo5vYSJdQt99Ksg.PNG/PJVZXssiCfANxfHToDAQ.png",
      career: [
        "2017 LCK Summer 우승",
        "2018 LCK Spring 우승",
        "2018 MSI 준우승",
        "2020 LCK Spring 우승",
        "2021 LCK Summer 준우승",
      ],
    },
    {
      id: 6,
      nickname: "Croco",
      name: "김동범",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjY5/MDAxNjg4NjI2NTIwODI5.5fE5xyAYAfDJGfMF15xAepjUYdIvzT6psvNhgJcgaLYg.t3jxKkC_9fKhKqmIaUlPWnR73fEShav18BfkVG6VCxgg.PNG/cbmFIkcgNQXFhRxpBIOj.png",
      career: null,
    },
    {
      id: 7,
      nickname: "YoungJae",
      name: "고영재",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNjkg/MDAxNjg4NjI3MTgzOTE4.kT0Z1ITGThCRhTrD_1pZB8ifk3yScT2yH-vZfXgc-9kg.LOeU-C6rqDRT9m59g7rQDZt_6oOwCL6ZHM833w3vhpUg.PNG/REAinRpcdQoZgbhPLBWm.png",
      career: null,
    },
    {
      id: 8,
      nickname: "Sylvie",
      name: "이승복",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfMjEz/MDAxNzA1NDU3MzYyNDI2.g-2cVvUb0d6fLePMeawtvh9nuPw0yQAFB8v9kC-XoGYg.6vVgbUGMCG13rf1nyrIDXCLrzOe6eCxRLeprYizH6fsg.PNG/UiPtmRYTEIYqOpGtoRKa.png",
      career: null,
    },
    {
      id: 9,
      nickname: "UmTi",
      name: "엄성현",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjg4/MDAxNjg4NjI1OTgzMjEy.fFo4Qd3gHXLRICKG4w0IrOdMTOBWxjiSFYcz8kDtbhkg.sKrTw5NLxCQ31j1nFP4fbI3ojY1OgE_iKziq1Yh7RLAg.PNG/rhDbhhbOCKgLSaYvctik.png",
      career: null,
    },
    {
      id: 10,
      nickname: "Grizzly",
      name: "조승훈",
      img: "https://nng-phinf.pstatic.net/MjAyMzA2MjhfMTEz/MDAxNjg3OTM2ODI1MDU1.m8QgNOzkrx-tsPaWanziQ-WYgUd9X_vKDjpjhOma9zkg.VdcC03xlD7MRNw_22y55xZmYOe0tcDdKw4m9Ft1Nt2sg.PNG/VRoIXgqrkdmFHcnyEKUc.png",
      career: null,
    },
    {
      id: 11,
      nickname: "Juhan",
      name: "이주한",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjM0/MDAxNjg4NjI2NTIxMDQ1.VxFvWX4tDAVYZKUnR-TMp-sNgxyi-CANBx3saG-JlaUg.q0jhrxduJGYlzPYWT1Oeyp98OKIAwqA01HLuGSLkpZ8g.PNG/UrgGLjgqupoHJzUHEfgu.png",
      career: ["2022 Worlds 우승"],
    },
    {
      id: 12,
      nickname: "Pyosik",
      name: "",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfNzMg/MDAxNzA1NDU3MzYxNTcz.wWG77PNxDrt1TQGH99nMGlXgzItvG34EnlV2aSUH9vQg.G6qZ4zJ2KNRkeANR4QQsy1lf4Lh2YSAcQsIWtzD05Q0g.PNG/MjXirXYiUyTLwdTkLZYd.png",
      career: ["2022 Worlds 우승"],
    },
    {
      id: 13,
      nickname: "Sponge",
      name: "배영준",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfMTIy/MDAxNzA1NDU2MTAyNzk1.9M04vssZL6jTqlC-xWYKJrN85pzaaEioevhdKY-Zi3Yg.aWrZiXNay7uOoe4wJGl_-cWMtIcdJik_r29M5fbGxJwg.PNG/wGqSyzVAdNefHKPqzIQf.png",
      career: null,
    },
    {
      id: 14,
      nickname: "Guwon",
      name: "구관모",
      img: "https://nng-phinf.pstatic.net/MjAyNDAzMDRfMTMg/MDAxNzA5NTI1NzIwNDA2.VFQxEiQt2uKpShKHo59hoFkGoHoSCSqwk3k8Sba6fIog.THK7hEUt7yqzKRDwn4rBDqI_FpspshdyvzpUhtrEJzQg.PNG/vUaneMXBMkgjbOlyGgJV.png",
      career: null,
    },
    {
      id: 15,
      nickname: "Gideon",
      name: "김민성",
      img: "https://nng-phinf.pstatic.net/MjAyNDAyMTVfODYg/MDAxNzA3OTkzNzQxNDI1.el7r8eUAX01rY0kTck04bCvl2riBMUIPgW83RK5Pkokg.J9BHwFOW1FBj06xM0YFXW7FBErqmqKNMQEbWzo58ffAg.PNG/EkvXzeSNXfySKERcirgG.png",
      career: null,
    },
    {
      id: 16,
      nickname: "DDoiv",
      name: "방문영",
      img: "https://nng-phinf.pstatic.net/MjAyNDAyMDVfMTEx/MDAxNzA3MTIwMzg0Mzc2.Y0riMLsTQHvptYJNSLWstQJ67o7Au5VBDqsBQ2yVlQ8g.bJvONOdhSLRJgG2EsjhhGA0079Zb_iAgoa9XvkAdY0og.PNG/mMtUrmnHsYKtbtbUNOPe.png",
      career: null,
    },
    {
      id: 17,
      nickname: "Hambak",
      name: "함유진",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTdfMTIz/MDAxNzA1NDUzOTQzMzc3.8IvId6W1LYpY8VcB9I4CJ1TsdiNmNnsTjymZ_KdqME4g.f6RUfUnWILfJ4m3Jn9EonY1J75t0CVh-3QNxKTfsXPEg.PNG/QKUISFfDnXRHZXJISHMp.png",
      career: null,
    },
    {
      id: 18,
      nickname: "Clid",
      name: "김태민",
      img: "https://nng-phinf.pstatic.net/MjAyMzExMTBfOCAg/MDAxNjk5NTk5OTIwOTQy.0QSrZ65PguLl6Js0IZcLpKQsabS91AoWh_BfVzvr1C8g.6yK1EHp0QQSPmOHdQdykm5v0nfKGy_BuLCYie_u5vrwg.PNG/TSqpRynTkKwKCnIvgYJt.png",
      career: [
        "2016 LPL Summer 우승",
        "2019 LCK Spring 우승",
        "2019 LCK Summer 우승",
        "2020 LCK Spring 준우승",
        "2021 LCK Spring 준우승",
      ],
    },
    {
      id: 19,
      nickname: "Dread",
      name: "이진혁",
      img: "https://nng-phinf.pstatic.net/MjAyMjExMjJfMzUg/MDAxNjY5MDgyNzc3MTQ5.N0eNbvOUHuCSNw4cUNuJiKaTj0hSG078bk24oKpDxMIg.ipHCkhcP-bgFIS-bx2OfvsZ8_1e-w6dgo0dyGojvRjMg.PNG/wKVCLzMwklyhWyZiMXLd.png",
      career: null,
    },
    {
      id: 20,
      nickname: "Onfleek",
      name: "김장겸",
      img: "https://nng-phinf.pstatic.net/MjAyMzAxMDRfMTA1/MDAxNjcyODA2ODU1NDA5.pEl5lyu3dMv9C95FCYJE48zwjlXVhuvMEl8IdXeUFa0g.0new2iqusp6BfzegpbHZHZ8nCu-lW6s30yo14lBt-lAg.PNG/EgpIMAfEdFUwUPgVbGmZ.png",
      career: null,
    },
    {
      id: 21,
      nickname: "Ellim",
      name: "최엘림",
      img: "https://nng-phinf.pstatic.net/MjAyMzA2MDJfMTQw/MDAxNjg1NjcyMTg0MjU5.AwFtg1Wv8-ltiZn4h9LtePStIPVCGQ06yxd1MTVdszMg.eQPpttUjPhG0V8cUE-lWqTqYXD7lTSNlu6ALg-XJM8kg.PNG/aPpIKUpoQdNDyjDBVrvb.png",
      career: null,
    },
    {
      id: 22,
      nickname: "Raptor",
      name: "전어진",
      img: "https://nng-phinf.pstatic.net/MjAyNDAxMTJfMjYx/MDAxNzA1MDQ0MDgyNzA5.WsRHetAxc9K4ZLFLlXjfhAHtdJLDTiumhTHSNltd_fYg.XIR5cxRlr1iDVYsNW5BDaLJxdVabYxo80ycAGSn-Ta8g.PNG/chbdKTzCpjSApPYYRbYb.png",
      career: null,
    },
    {
      id: 23,
      nickname: "Malrang",
      name: "김근성",
      img: "https://nng-phinf.pstatic.net/MjAyMzA0MjRfMjUg/MDAxNjgyMzAwMTIyMTcy.7YwVj0N6nChEv1DSSzXXRCe8oXKZjrMK7ctO7rb-NEwg.C_2t3Yd-siejF3xcsiNTm4j9Ta7wS6uJvGEhB8-hFrgg.PNG/JOHADmfjFCNazJVkGUJZ.png",
      career: ["2021 LCK Summer 우승", "2021 MSI 준우승"],
    },
    {
      id: 24,
      nickname: "Arthur",
      name: "박미르",
      img: "https://nng-phinf.pstatic.net/MjAyMjA0MTFfMjg3/MDAxNjQ5NjQwMDE3OTk5.GDPSSRmNSKZ9gmUE9oxAKeBs_eCxCZUiUtsULtLmp9Ag.xA8gIgJ4-xFj5pNP4XlvZHqMEtpuoKMrmwToJme7GVgg.PNG/zncMtHCIOeImsYCqAUui.png",
      career: null,
    },
    {
      id: 25,
      nickname: "Blank",
      name: "강선구",
      img: "https://nng-phinf.pstatic.net/MjAyMjEyMTJfMjg5/MDAxNjcwODA0Mjk1MjIz.D_T8L6CK4b8-aw5sv49WFJlP4ZsgIfuuq83DxeB5SZcg.EpBdf8hAaURqnS_KL0hh0ypHKFIXSWHqaqYrI5wt3ycg.PNG/JBtzNoCUkHPEJmXWIhKK.png",
      career: [
        "2016 LCK Summer 우승",
        "2016 MSI 우승",
        "2016 Worlds 우승",
        "2017 LCK Spring 우승",
        "2017 MSI 우승",
        "2017 LCK Summer 준우승",
        "2017 Worlds 준우승",
      ],
    },
    {
      id: 26,
      nickname: "yohan",
      name: "김요한",
      img: "https://nng-phinf.pstatic.net/MjAyMTExMjZfMjQ3/MDAxNjM3OTE5OTEwOTIy.0pzUJL3M4yY5MyrMIEg8GyEpqXU6-JfdHNUlmLp2cfIg.0i3XSIpcAunMoyxao2XSn_aXyUqCJ1BJuI110TPU8ggg.PNG/POoKOurVFHnJXPuYpueZ.png",
      career: null,
    },
    {
      id: 27,
      nickname: "Flawless",
      name: "성연준",
      img: "https://nng-phinf.pstatic.net/MjAyMTExMTZfMTIy/MDAxNjM3MDIzODcyMTIx.sbHY8wQaqbMAJMsPN-pnN_Wp1bZyaGMwrfP_1ls7PW0g.-AaYwgpuLT9PUSj49UTQiifrQKcN4QV2DeP-3NRqfCAg.PNG/dCiKVKnxmQBAFeglbKps.png",
      career: ["2019 LPL Summer 준우승", "2021 LCK Spring 준우승"],
    },
    {
      id: 28,
      nickname: "Bonnie",
      name: "이광수",
      img: "https://nng-phinf.pstatic.net/MjAyMzEyMTFfMjgx/MDAxNzAyMjg1MjIzMjEx.SvlWkTLufnN4FJBbcqhJTbFO63XTJGosrmYm5Tj1XsYg.B0ZAxM8s2EPBpGTBODmuDv_1txHHlKwpYwfpPneG2Msg.PNG/QcfhWxsxEKoodvLtIvrA.png",
      career: null,
    },
    {
      id: 29,
      nickname: "Chieftain",
      name: "이재엽",
      img: "https://nng-phinf.pstatic.net/MjAyMjA1MThfMjkg/MDAxNjUyODQ2NjU2MjIy.j0spzj0uiYHgah73C78ssTCcn8MFidDbEdOohamZ_4Qg.UBEBXVlGjv3UOR_R0tWVvjX_GJ9P6cdEtxpLmC6c4N4g.PNG/BdJOGpsIIMwRlaQRirDB.png",
      career: null,
    },
    {
      id: 30,
      nickname: "Spirit",
      name: "이다윤",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfMTIw/MDAxNjE0MTcyNTcwNDgz.yHdwqoWJYCJR9GSPnqCM-O4tbYkrrfcDvcn14IuprXQg.RVHG_9uHm1_LZDYe244BB8CCBUx-nBzJr5oTSVtTCRYg.PNG/PLCZuXCDMsMUCHZsYQxx.png",
      career: [
        "2014 LCK Spring 우승",
        "2014 LCK Summer 준우승",
        "2018 LCK Spring 준우승",
      ],
    },
    {
      id: 31,
      nickname: "bono",
      name: "김기범",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfMjUy/MDAxNjE0MTcyNTc1MTk4.RdOd9zGECspemHSHTKi5ajOdlWet8J0Clo9Mfk16-rIg.D_LjRLhhkCNBEsVA5T3hVw8Y7Ezy3FkiWv1LLYvAkVMg.PNG/gUAjrDvFFKzoNvjDkyvN.png",
      career: null,
    },
    {
      id: 32,
      nickname: "Beyond",
      name: "김규석",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfMjgg/MDAxNjE0MTcyNTczMzU3.Lm2iDDoiBksHBkfuXkpOZBpTLXjULHYn08tzqFaWgJMg.ziUK_cuqGB8W6FIMlPZzBmZjVh0fxQTJjxT1iL7j2Wgg.PNG/bQdrwoKCrlwPFOXfKlpM.png",
      career: null,
    },
    {
      id: 33,
      nickname: "Cad",
      name: "조성용",
      img: "https://nng-phinf.pstatic.net/MjAyMTExMTJfMTQx/MDAxNjM2Njg0MjEyMTYy.GItBw86JdJpk7jt6I7_-1yK-E76QnBbi7p241L6VzEYg.o4zoWgMK22sQFes1S5JuBu_aDDQRqygq3JsFxdLjnBAg.PNG/CsnDaPmoIcQZyMaxZVeF.png",
      career: null,
    },
    {
      id: 34,
      nickname: "Haru",
      name: "강민승",
      img: "https://nng-phinf.pstatic.net/MjAyMjEyMjNfMjc0/MDAxNjcxNzU3MTU1MzU5.KJVBWomRPQRKh9HXHrWzWpQGn4uF_OzxhqonwtFWXzkg.f2A42U02n_RhJBia29LLmZ9xtNS6L0qj08j7et3qRSkg.PNG/CnINPKNAiktoqPmYKcas.png",
      career: [
        "2017 Worlds 우승",
        "2019 LCK Spring 우승",
        "2019 LCK Summer 우승",
      ],
    },
    {
      id: 35,
      nickname: "Kuma",
      name: "박현규",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfNjMg/MDAxNjE0MTcyNTc2MTMx.k3GO7yaR-UsSKvT2ardHoEFQedT-KphqHBv9YOaVXSkg.7zj-lPk0PUm_BdOFoTGhfQyXIYIsu5fBsMWdBvK7MVUg.PNG/wgDyoRJOKhzWWIvdZckC.png",
      career: null,
    },
    {
      id: 36,
      nickname: "Punch",
      name: "손민혁",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfMTE4/MDAxNjE0MTcyNTczODE3.3QImjkpzBHcIXls26t71ErdmAlu_OPqhQCSGWbqXEH8g.dtDscoXvEOJemDrPTSqxCqcvQhHCz8Gw40N-x31CRYcg.PNG/NYgeUloqomvfYcUuabmT.png",
      career: null,
    },
    {
      id: 37,
      nickname: "Tarzan",
      name: "이승용",
      img: "https://nng-phinf.pstatic.net/MjAyMzEyMTJfMTA3/MDAxNzAyMzc0NjIzNzUx.BUSyx32w3NISboBkjrI8-T09mghYc-y0rAnn4mrPxrAg.ntfCukAWJBw9-eOWHOhnA-jwgGrudf9lE2p5pSc0Drgg.PNG/BCmrrZZsvPzYaeoxHdUx.png",
      career: [
        "2018 Worlds 준우승",
        "2019 LCK Spring 준우승",
        "2019 LCK Summer 준우승",
        "2023 LPL Summer 준우승",
      ],
    },
    {
      id: 38,
      nickname: "Score",
      name: "고동빈",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfMTI4/MDAxNjE0MTcyNTcxNjQ2.XdS-15fYI-Y3jcYkVPx1vXs7DnnzooQD_X99hOlUIakg.7h6bM_VU2peXnPABVmENmXDon7ijeL21w5pOZUaQ4Cgg.PNG/rSIvdxhmXxSEsMHNPZeh.png",
      career: [
        "2013 LCK Summer 준우승",
        "2015 LCK Summer 준우승",
        "2016 LCK Summer 준우승",
        "2017 LCK Spring 준우승",
        "2018 자카르타 아시안 게임 은메달",
        "2018 LCK Summer 우승",
      ],
    },
    {
      id: 39,
      nickname: "Seonghwan",
      name: "윤성환",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfMTgz/MDAxNjE0MTcyNTcyNTg1.53YbJnbaWB2lCTlHLXtSieIm5szb4kX1EixxyLyotRMg.Sy_sflXyhb3_cEBfLHD_RA0K_ap8SWjoQpNly9labs0g.PNG/fzmhgoGQvTnKKpSgGvBY.png",
      career: null,
    },
    {
      id: 40,
      nickname: "Moojin",
      name: "김무진",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfMjMw/MDAxNjE0MTcyNTc0ODA3.f0ylL2-A65eD-Vl3L1MWKAUkVzFUTBld-tgsZuswKGMg.IDyWI9GcXrZVEey67TrZBYTSrbERxCa4_0YJUu3Fg84g.PNG/ZWprkFgKyCrXmWtLERTF.png",
      career: null,
    },
    {
      id: 41,
      nickname: "Seize",
      name: "김찬희",
      img: "https://nng-phinf.pstatic.net/MjAyMTExMTZfMTY1/MDAxNjM3MDIxNzczNTYy._18kZHyY-EPEY9_eXdiuCrVeWdXo47rpagqEAyLvBlQg.RR96Po4VHYKldymH61ic5oxMyVrh9iCQOgy1GzzuilAg.PNG/UrMicyAHnvRmNDFNFAcK.png",
      career: null,
    },
    {
      id: 42,
      nickname: "Crush",
      name: "김준서",
      img: "https://nng-phinf.pstatic.net/MjAyMTAyMjRfMjUw/MDAxNjE0MTcyNTcyNjU4.1lBOhH2-fJaZULZaETVEuLrb87LqDhNEepqHKZaQQDAg.QRFLun230Y80JZHfvCwOwVvWPvP91Nzgxy3-kWwdPEAg.PNG/nnfmcEybbXJbLBnnchjb.png",
      career: null,
    },
    {
      id: 43,
      nickname: "Kakao",
      name: "이병권",
      img: "https://nng-phinf.pstatic.net/MjAyMjA1MTdfMTQ0/MDAxNjUyNzc4OTc4MDUw.4uKN6DtWmob0eb9P-wUSWFR2FbwcU-9QY696bGvX4R0g.NJl67LWi8gKGACIaW06L2j_0OTxvrHQM5vSpkoDxuiYg.PNG/iOWWOqcbCzlllQLYfPQw.png",
      career: ["2013 LCK Summer 준우승", "2014 LCK Summer 우승"],
    },
  ],
  mid: [
    {
      nickname: "Chovy",

      name: "정지훈",
      img: "https://nng-phinf.pstatic.net/MjAyMzA5MTJfMjU5/MDAxNjk0NDk1OTAyMDg2.I3pk7iAV1VKXSB8Ff1p2wL7fU8WDjmz2pF91oc6-oJYg.BoPps967Yp4BGCY_7vcnDCBq4BRmdIKLoe6HWApcDcMg.PNG/pdjSFwSEtFgMKMPSNwSk.png",
      career: [
        "2018 LCK Summer 준우승",
        "2019 LCK Spring 준우승",
        "2019 LCK Summer 준우승",
        "2020 LCK Summer 준우승",
        "2022 LCK Spring 준우승",
        "2022 LCK Summer 우승",
        "2023 LCK Spring 우승",
        "2023 LCK Summer 우승",
        "2022 항저우 아시안 게임 금메달",
      ],
    },
    {
      nickname: "Faker",

      name: "이상혁",
      img: "https://nng-phinf.pstatic.net/MjAyMzA5MTJfMzAw/MDAxNjk0NDk1OTAxNjUz.6EuCErf8L5Aivu_KhCPlseZodKe8gQcKTYeLNGn36wEg.YUMZ2itQzzguv-M1oN-YocXz6uG3syCEhJTbA_ZEL9sg.PNG/gXrqiGOJgAnmyuGnuTHU.png",
      career: [
        "2013 Worlds 우승",
        "2015 Worlds 우승",
        "2016 Worlds 우승",
        "2017 Worlds 준우승",
        "2022 Worlds 준우승",
        "2023 Worlds 우승",
        "2015 MSI 준우승",
        "2016 MSI 우승",
        "2017 MSI 우승",
        "2022 MSI 준우승",
        "2013 LCK Summer 우승",
        "2013 LCK Winter 우승",
        "2015 LCK Spring 우승",
        "2015 LCK Summer 우승",
        "2016 LCK Spring 우승",
        "2017 LCK Spring 우승",
        "2017 LCK Summer 준우승",
        "2019 LCK Spring 우승",
        "2019 LCK Summer 우승",
        "2020 LCK Spring 우승",
        "2021 LCK Summer 준우승",
        "2022 LCK Spring 우승",
        "2022 LCK Summer 준우승",
        "2023 LCK Spring 준우승",
        "2023 LCK Summer 준우승",
        "2018 자카르타 팔렘방 아시안 게임 은메달",
        "2022 항저우 아시안 게임 금메달",
      ],
    },
    {
      nickname: "Clozer",

      name: "이주현",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTg2/MDAxNjg4NjI3NTQyNjA3.3sq9MK2CoQJjyIc7kdl5BwvfTqedTHXFg4_fH_FHHYog.qmdTvyzfigYiLRgO0ClW9IAh-Ui-MlWCtEnhMqOzyUEg.PNG/jpqHdpJlJXbpXtSZzGFu.png",
      career: null,
    },
    {
      name: "허수",
      nickname: "ShowMaker",

      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNjkg/MDAxNjg4NjI2MjgxODY2.BoeCECtrPFWDo6ThpeQzO3PzgV2qibpdiU1iSEKNdLcg.juPAc58Q5TkQf_zADiblv6dEvqIYJA-diIhXkSsv_sgg.PNG/ESNbuesnzTdvAEXklQcZ.png",
      career: [
        "2018 LCK Summer 우승",
        "2020 LCK Summer 우승",
        "2020 Worlds 우승",
        "2021 LCK Spring 우승",
        "2021 MSI 준우승",
        "2021 LCK Summer 우승",
        "2021 Worlds 준우승",
      ],
    },
    {
      nickname: "Bdd",
      name: "곽보성",

      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNjYg/MDAxNjg4NjI3NDIzNTM1.O4NR_DOVfgTmrPzRyVHMs3F2nQVnfvbuPAC1c3Qbwyog.aJ6_wTBpOm8wSOiOpfl29a1OUlfz5JM9Ss-9CKf6CAIg.PNG/SmtigQzkZARtxtEyELqv.png",
      career: [
        "2017 LCK Summer 준우승",
        "2018 LCK Spring 준우승",
        "2018 MSI 준우승",
        "2020 LCK Spring 준우승",
        "2021 LCK Spring 준우승",
      ],
    },
    {
      nickname: "Fate",
      name: "유수혁",

      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjA0/MDAxNjg4NjI2NTIwNjU4.GdJNcqhph9iWhZERNfBwLJLkd0are_SWzol2YsuAlXgg.1G667dU2OPcbU5oROwZ8RGnljiEMxfsIN2OakqJ8vzYg.PNG/CedChAZMzUksWanABPKK.png",
      career: null,
    },
    {
      nickname: "Bulldog",

      name: "이태영",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNzMg/MDAxNjg4NjI3MTg0MDYx.AKj10Oe4jx1us43eKn59QQrlbtSwgJjEH017De02uLYg.p4MrWxGdx19HT-qW8XWcMOWNShNAghoXII_03wpCVEwg.PNG/UsJHwkNxOKjTYWIDBSnZ.png",
      career: null,
    },
    {
      nickname: "Fiesta",

      name: "안현서",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTM5/MDAxNjg4NjI3Nzg0MDI2.PE2VocRptLcIisQV2JFcus6uMwe0Ttf3xhg4w1f0Lnkg.uEiCVK3EC4I6W3_scD0WYtTU4vVEDs47A98nUsTG-78g.PNG/OSblyqXBBbpfRKDxrKtK.png",
      career: null,
    },
    {
      nickname: "Karis",

      name: "김홍조",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjk2/MDAxNjg4NjI2MTAxMDY0.EtBAoyvf1ReM27v972Awp2tYUzblH4M0SVxROvcpDkkg.4rptOe_oEVGWyWEq1rKGRBMKlRKMbhPCTPj9lQIXJhQg.PNG/TcDKavblnkzXnIKdpmZz.png",
      career: null,
    },
    {
      nickname: "Zeka",

      name: "김건우",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNiAg/MDAxNjg4NjI2OTQxNzg3.NO_J7PQ1mA-bpLqiv0Npu35QphljeUTsMPJVvgVVb-wg.RkEru7_VXYLFGYVzmcAIcckIzJuUAz1X8Kar5tgSEkcg.PNG/JCZqkVvxbkADSfemqfjo.png",
      career: ["2022 Worlds 우승"],
    },
    {
      nickname: "Sky",

      name: "김하늘",
      img: "https://nng-phinf.pstatic.net/MjAyMzA1MjVfNzIg/MDAxNjg1MDA0MzIwMzQ1.DKoMsIy2vmo_xut658TeEp49Gst2AUuyqgs3jeFcoOEg.Z0HAt0J6JtUl8sva86nyd6ssKDLyYwq2CLNcbkTvskgg.PNG/RznuclZJKsfawhNewaIZ.png",
      career: [
        "2017 LCK Spring 우승",
        "2017 LCK Summer 준우승",
        "2023 LCK Spring 우승",
        "2023 LCK Summer 준우승",

        "2023 Worlds 우승",
      ],
    },
    {
      nickname: "kyeahoo",
      name: "강예후",

      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNDQg/MDAxNjg4NjI2NTg1MzMw.QFgZ-WSSVnYYch9n29jhPGKTDyG8vuBB1Cd_An3p2pYg.zh1iVfE7j4WmxoQxcQ4T4Kgz5jyG0ZCSO65M770c6cIg.PNG/FPWWdmJcUnkaXUiGtqJY.png",
      career: null,
    },
    {
      nickname: "Quad",

      name: "송수현",
      img: "https://nng-phinf.pstatic.net/MjAyMzExMjBfMjgw/MDAxNzAwNDUzNzgyNzY5.u_FM6kUn8qdGKbbNFuesnIr4gmBsYPw93dfNrGogyY8g.TzA5WZTxXow3Omse1HsfDurJ7aQmUasUcIaQ7agr6Hkg.PNG/NkJjkcvVXdBHrLXLGOFv.png",
      career: ["2020 LCK Summer 준우승"],
    },
    {
      nickname: "Callme",

      name: "오지훈",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDdfMTQz/MDAxNjg4NzA0NTIxODE2.r0jhqKCLb_wDOV0GBjCAyayTPHpcfKgseA1kSxvs9K0g.qKGCfhm0UPn325tUskKFEE_m6naiqVM2LeOkSzcEKNMg.PNG/FDVSjODXyaFJvLZSaslj.png",
      career: null,
    },
  ],
  ad: [
    {
      nickname: "Peyz",

      name: "김수환",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfODUg/MDAxNjg4NjI2NzAyMzY1.XmNiFz3E8Uw0GTXH0DkNXjTn5A-46-gW50DjLU1OZCEg.nxXvEzt_xdYF_iqivarZ0sDlPZeWDLfke06BSscnXScg.PNG/HUlabcQzATblGRFRdjNn.png",
      career: ["2023 LCK Spring 우승", "2023 LCK Summer 우승"],
    },
    {
      nickname: "Gumayusi",

      name: "이민형",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTQ5/MDAxNjg4NjI3OTAxODAw.4R26_85nhfHh6mRAQE_Rpz0gVEAbL7bE7N5DcmnkdGYg.Eavo-ibB2RjjDim3DMWMXUQaM-05TPcEyypyJR_aBQgg.PNG/tqFJNzRLwkUkHvHOcIrP.png",
      career: [
        "2020 LCK Spring 우승",
        "2021 LCK Summer 준우승",
        "2022 LCK Spring 우승",
        "2022 MSI 준우승",
        "2022 LCK Summer 준우승",
        "2022 Worlds 준우승",
        "2023 LCK Spring 준우승",
        "2023 LCK Summer 준우승",
        "2023 Worlds 우승",
      ],
    },
    {
      nickname: "Teddy",

      name: "박진성",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNjEg/MDAxNjg4NjI3NTQyMDg1.MeV3ofplLe0ax2_5LoZn0Zz9pDBmO90q-PE9RPcDfdMg.e3YNxjbjluz3_aQDK3EVaiCqfJtoVkGSrU_dpk7bPwog.PNG/YeKkZnSavYhYBsbmWjsg.png",
      career: [
        "2019 LCK Spring 우승",
        "2019 LCK Summer 우승",
        "2020 LCK Spring 우승",
        "2021 LCK Summer 준우승",
      ],
    },
    {
      name: "김혁규",
      nickname: "Deft",

      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjE5/MDAxNjg4NjI2MjgxMzU5.LU3A1PCn1dcdHSjQ37b-CCoz3gB_clwhC2k0fPk3gjcg.g9tu2_6ztHBJJUOx8kM015NgQqmohlM8I8jy-MQrwjwg.PNG/LiKaKksCGlQzWtVZDRwF.png",
      career: [
        "2014 LCK Summer 준우승",
        "2015 LPL Spring 우승",
        "2015 MSI 우승",
        "2016 LPL Spring 준우승",
        "2016 LPL Summer 우승",
        "2017 LCK Spring 준우승",
        "2018 LCK Summer 우승",
        "2020 LCK Summer 준우승",
        "2022 Worlds 우승",
      ],
    },
    {
      nickname: "Aiming",
      name: "김하람",

      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfODYg/MDAxNjg4NjI3NDI0NTU1.6L-zbydHCWVyd7IUrpg_m6SQRNFMeabcl1mSsj5gVwsg.loEZVFLwwf9_VjGUJxR3EWbnJV0HlEW1W6-Go2_QCEIg.PNG/dQuXNdnXAssyRxatoXjD.png",
      career: null,
    },
    {
      nickname: "Paduck",
      name: "강예후",

      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTc0/MDAxNjg4NjI2NTIxMTk1.0L1GQQd9EgEkiz8IjAIxGcypGrUpv_Jw7Dcb88i_eXsg.ZvnASB6FL7BzNHE1HD6Tcn3PWXfDwQV_JQUE3RcnBiAg.PNG/ANgiWOtLMcEvxntUpBEP.png",
      career: null,
    },
    {
      nickname: "Taeyoon",

      name: "김태윤",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTg0/MDAxNjg4NjI3MzAxOTg4.pF1NBKSOZq7Q5Kg-yCRwcGMer_cvOpIp5loXxt4OXLQg.TePjDCV4_9H2sV1PG3mD45wQsC3lzLDWoLFEP1EIAzMg.PNG/UulMlUmhzvncQjUdsxUM.png",
      career: null,
    },
    {
      nickname: "Jiwoo",

      name: "정지우",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDdfNTIg/MDAxNjg4NzA0NTIwODQw.oZ0C7mo26zksWrCDLB2QhW3Lf2f9645K_YMw8yyYjK4g.n-L1TqIOPuWoQzVkgQYsAXX4oLuCKOWM1j3PcKgKZY4g.PNG/HQvVmLEIAfwSZvsreAJx.png",
      career: null,
    },
    {
      nickname: "Hena",

      name: "박증환",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDdfMTg1/MDAxNjg4Njk0NzQwNDc1.EZ63TsaBhpfzXPGszO-B79IciBM9bBBOMwrNJrFbZYgg.r5frdLLsoDXE5r3CbljeRbBAwzbYTncUyc9R_Jy6RCAg.PNG/QUNCZXnofxzHtTCUPBch.png",
      career: null,
    },
    {
      nickname: "Viper",

      name: "박도현",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjc2/MDAxNjg4NjI2ODgzMjQw.4Ob59OesRDTDhfW3eqkWXhSev-mrXVL1iWqIqGdpT50g.WgtAo66XjNjN5TDzhZWM3KJ0ejFwYrOHHZLpeWZTb9cg.PNG/hqjAhhuOUsBmjasYzCKy.png",
      career: [
        "2018 LCK Spring 우승",
        "2018 LCK Summer 준우승",
        "2019 LCK Spring 준우승",
        "2019 LCK Summer 준우승",
        "2020 LPL Summer 우승",
        "2021 Worlds 우승",
      ],
    },
    {
      nickname: "Deokdam",
      name: "서대길",

      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTkw/MDAxNjg4NjE2NzQyNTkz.MAkdO2rYyyITLAwk8903GIUf6oMVRWeWHDAAdjOfD9Ug.8Carzr6vOSFCGWvq6NPzp-ThAiz6xduVCVxSsNz7Go0g.PNG/KwFHjypwcQmutPkoDTIc.png",
      career: null,
    },
    {
      nickname: "Pleata",
      name: "손민우",

      img: "https://nng-phinf.pstatic.net/MjAyMzA3MTBfMTYz/MDAxNjg4OTc3NTg3MjY4.0ajhQlxJbmoA6okuGUtgGo-T43ptodq71BkRhN-NyHwg.0G6jQlNpdymCPoDRTnX4OYrg5gjGhCysI60lUdx6vS4g.PNG/oYtAJvtWdFvvipZlTBSz.png",
      career: null,
    },
    {
      nickname: "Vital",

      name: "하인성",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNzAg/MDAxNjg4NjI3Nzg0Mjgx.xrUgzG0ZRYg4NqgPeUQ5Zh109_vB00qmjFFQqSb6CLQg.UuGSljjZbZu3nbdKfLpAfzCObXiGJEUhJWqu74HuQjgg.PNG/GrVgThejeKoKenBFXHYi.png",
      career: null,
    },
    {
      nickname: "Envyy",

      name: "이명준",
      img: "https://nng-phinf.pstatic.net/MjAyMzA1MjVfMjUz/MDAxNjg0OTkwNzAxMTAy.926BY08zcO17raZQMx4D-Zb0csSh0kIDJuOTnN1rE6sg.6F-hhTuXOeg1PAevU6sEou1gp-d1rHuqHUiKk0ri_7Eg.PNG/pnxjnlgzCKXMuZWsxlJC.png",
      career: null,
    },
  ],
  spt: [
    {
      nickname: "Delight",

      name: "유환중",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTk2/MDAxNjg4NjI2NzAyMjM2.5YsKPhIqcp6lTAdafm7Qo2LIgGgaDbthjPaQfT0CCaQg.P5Cls70UFR3UHBWgPsk15Px1KucvHJDd9yL1lqqREMog.PNG/DXASSvCWFKuNJAAmYGwd.png",
      career: ["2023 LCK Spring 우승", "2023 LCK Summer 우승"],
    },
    {
      nickname: "Keria",

      name: "류민석",
      img: "https://nng-phinf.pstatic.net/MjAyMzA5MTJfMjYz/MDAxNjk0NDk2MDIyODAy.U0124KDUBZG5pcIZvhkrnGZb1g4z-6dGEfhu1PZPxrog.-ebhr0BHM3T2Vp3q1ED1V4DJvjBf_y9llld4HRoqIhsg.PNG/RjRBpHNOORsmoouTTRtp.png",
      career: [
        "2020 LCK Summer 준우승",
        "2021 LCK Summer 준우승",
        "2022 LCK Spring 우승",
        "2022 MSI 준우승",
        "2022 LCK Summer 준우승",
        "2022 Worlds 준우승",
        "2023 LCK Spring 준우승",
        "2023 LCK Summer 준우승",
        "2022 항저우 아시안 게임 금메달",
        "2023 Worlds 우승",
      ],
    },
    {
      nickname: "Kael",

      name: "김진홍",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTEx/MDAxNjg4NjI3NTQyODg2.O5zPc_XhdpmLZkjQrzhe-l0YjIgAUoCh97RBigBM8eQg.MGdSkpJE1KFFknjlv-lIzi1XhlsHy-3ZcEsF6e_JDC8g.PNG/BUWBFGbiomYXVrXMPDmS.png",
      career: null,
    },
    {
      name: "김형규",
      nickname: "Kellin",

      img: "https://nng-phinf.pstatic.net/MjAyMzA3MjhfMTYz/MDAxNjkwNTMxMTYxODEx.6FQqHY3LXv6X2BfHgtQenZAwT9BDDTyXqDaE8BCkze4g.CdZuRXIfp_JSWfLhBXwbvzy4c9sPm6ryo6F0uxBHA44g.PNG/GdOeNXQWOESCWyitozEU.png",
      career: ["2020 LCK Spring 준우승"],
    },
    {
      nickname: "Lehends",
      name: "손시우",

      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjA1/MDAxNjg4NjI3NDI0MDcy.jcZS7whHzycRYqjcOjPAek1SOjdmdIZU5iAfzvAdPSYg.ABFcnMgZ-jcjmqjoo5XFAnhMBN5qno1gPo7WiJez6Xog.PNG/gDXhalcICcdGUeMcqcPD.png",
      career: [
        "2018 LCK Summer 준우승",
        "2019 LCK Spring 준우승",
        "2019 LCK Summer 준우승",
        "2022 LCK Spring 준우승",
        "2022 LCK Summer 우승",
      ],
    },
    {
      nickname: "BeryL",
      name: "조건희",

      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTAy/MDAxNjg4NjI2NTIwNDk3.h89wLhpZobkjUP7cYavwefe6-fD0wAMQg6rbbdKfXQ8g.5NSp2C6XSFRsqhHiryF7vrSn1NJpmBVBTTYtWCVpiXQg.PNG/dihOEhbTyHFTLQMYFiWk.png",
      career: [
        "2020 LCK Summer 우승",
        "2020 Worlds 우승",
        "2021 LCK Spring 우승",
        "2021 MSI 준우승",
        "2021 LCK Summer 우승",
        "2021 Worlds 준우승",
        "2022 Worlds 우승",
      ],
    },
    {
      nickname: "Jun",

      name: "윤세준",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNjkg/MDAxNjg4NjI3MTgzOTE4.kT0Z1ITGThCRhTrD_1pZB8ifk3yScT2yH-vZfXgc-9kg.LOeU-C6rqDRT9m59g7rQDZt_6oOwCL6ZHM833w3vhpUg.PNG/REAinRpcdQoZgbhPLBWm.png",
      career: null,
    },
    {
      nickname: "Peter",

      name: "정윤수",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjI4/MDAxNjg4NjI3Nzg0MTIy.KE1uNehdH-YU1mpVEufg5AUruDJe3eo4ryCza58djWYg.vuLkwclGbTNyGowPEMelaXvixEWWANlEbSWulGsQa7wg.PNG/zNgOYNBMfTrjrwQUPhLJ.png",
      career: null,
    },
    {
      nickname: "Effort",

      name: "이상호",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTA3/MDAxNjg4NjI1OTgzNzQy.TBHp69eynJ7GgPlFh0J9fkz_q7r36aVXB9e2xOlJjOwg.raQFzuPtZDxMRnsOmfTOZi9N9hwAeYHNCgo3MwfyQ9Ag.PNG/ewEebpNfimQuLMrihYUt.png",
      career: [
        "2019 LCK Spring 우승",
        "2019 LCK Summer 우승",
        "2020 LCK Spring 우승",
      ],
    },
    {
      nickname: "Life",

      name: "김정민",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTAy/MDAxNjg4NjI2ODgzNDUy.PlhmyoEEgppJACBqOIsTlJyxBRlpIRgaSWL1zdto6KMg.POgG4_i-jO23hDIcxIk_s3ftVtaxEccPNQTOnkVMEc4g.PNG/lboQwgbUEGPCvsjTCuAY.png",
      career: ["2020 LCK Spring 준우승", "2021 LCK Spring 준우승"],
    },
    {
      name: "윤설",
      nickname: "Bible",

      img: "https://nng-phinf.pstatic.net/MjAyMzA3MjhfMjIg/MDAxNjkwNTMxNDYwNzUy.f5zv6SCex3xZrtatFwVhRPXh7J6G68Ce1-a8XA7MkV8g.VsRmpiJ9bmMCFenHVrmbrKn5lW-oDSKv-33iP4Mh1p8g.PNG/LUNyYQVIMgEROuuIKdJi.png",
      career: null,
    },
    {
      nickname: "Andil",

      name: "문관빈",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDlfMTkw/MDAxNjg4ODg4NjAwOTI5.8VFcl9z3-3OpDBHRVuvuDMKNPeGvbNHz-f8em6XhSlog.zbXS_uJxQS_rPoPTiGxAqtUQayYd64O5Fa4l6kLZiiIg.PNG/POrqUpKXMgATsjuqzWms.png",
      career: null,
    },
    {
      nickname: "Moham",

      name: "정재훈",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDdfMjcx/MDAxNjg4NzA2MjAwNTQ2.btcz_I9WUh73XJYH5OGRuztWMkCxB08_xLmC-FC1xEcg.qNazYSk6oerbYDjBg2i0iCg6XWBdY2o_epKitDtrXWog.PNG/PJyGmWxKDFoJUadjrwAP.png",
      career: null,
    },
  ],
}
