export const players = {
  top: [
    {
      id: 1,
      nickname: "Doran",
      team: "Gen.G",
      name: "최현준",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjUz/MDAxNjg4NjI2NzAyMDkx.DBld4hTn99_IGSF1eZacPD1jQjxqNnTm19YV4yCLiL4g.r84zu-kgCNsJk7Dbm6rFtj6fznFL-foBmcj537tQ78Ug.PNG/iSUNFrWXXDGDgSQEHJfJ.png",
      career: [
        "2019 LCK Summer 준우승",
        "2020 LCK Summer 준우승",
        "2022 LCK Spring 준우승",
        "2022 LCK Summer 우승",
        "2023 LCK Spring 우승",
        "2023 LCK Summer 우승",
      ],
    },
    {
      nickname: "Zeus",
      team: "T1",
      name: "최우제",
      img: "https://nng-phinf.pstatic.net/MjAyMzA5MTJfMjc5/MDAxNjk0NDk1OTAxNzky.VCK0Hke_4ezSS7XGbQgFwv1wWMZckAyvX6lWl1vBkVUg.mHaJl_J_wLve7kJgrJ9G18sXPRX1plAiQhenJVkEn3gg.PNG/vKSveLgIomQlJKGkTSpH.png",
      career: [
        "2021 LCK Summer 준우승",
        "2022 LCK Spring 우승",
        "2022 MSI 준우승",
        "2022 LCK Summer 준우승",
        "2022 Worlds 준우승",
        "2023 LCK Spring 준우승",
        "2023 LCK Summer 준우승",
        "2022 항저우 아시안 게임 금메달",
        "2023 Worlds 우승",
      ],
    },
    {
      nickname: "Burdol",
      team: "리브 샌드박스",
      name: "노태윤",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNjEg/MDAxNjg4NjI3NTQyNzE3.DJmS6bDrfOuE4C250MkAalFP3-hvLwpptOwptmh7zm4g.BKecVPWDiegODFuWF59GosqLPpcg1h8ElloHm96H5wEg.PNG/bMmXXfYfMwpQACpsuLxw.png",
      career: ["2021 LCK Spring 준우승"],
    },
    {
      name: "김창동",
      nickname: "Canna",
      team: "Dplus KIA",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjQ5/MDAxNjg4NjI2MjgyNjUz.CXxzGtuUDTLlRSBeTW559QZFffr3Vc3dBHAapO5835Ig.vC7uAm6ja53Woh6C63TcMp_PdtvuWsTcZb8wJf7NYWcg.PNG/psHuWoAaEOYtglFGopOf.png",
      career: ["2020 LCK Spring 우승", "2021 LCK Summer 준우승"],
    },
    {
      nickname: "Kiin",
      name: "김기인",
      team: "KT 롤스터",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjM1/MDAxNjg4NjI3NDI0NDAz.QT1ryYAlw2Y_AZNxaLgIBKHlu8_mebb1p-uVJt2M5_og.s4cUq6s-BlBaRZZW1KcvL_GoHp9_GbZHnVA0CqmC-X8g.PNG/NHvuUvAXwxDlKXHuROIG.png",
      career: [
        "2018 LCK Spring 준우승",
        "2018 자카르타팔렘방 아시안게임 은메달",
      ],
    },
    {
      nickname: "Rascal",
      name: "김광희",
      team: "DRX",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjY3/MDAxNjg4NjI2NTIwMDQ2.6j0zL6rj68pcqJ1Yqr1H7MUkjPDduQRxVK3TWLBwmZ0g.-58IdYo5eC9HuZbFisILM8zozNisNfzDBXPrMTkWDZ0g.PNG/nmhmYXPPYjUtCTzINrUO.png",
      career: [
        "2017 LCK Summer 우승",
        "2020 LCK Spring 준우승",
        "2021 LCK Spring 준우승",
      ],
    },
    {
      nickname: "DuDu",
      team: "광동 프릭스",
      name: "이동주",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTQz/MDAxNjg4NjI3MTgzNDk2.ZaWxmy_rxreoJ6hAEwKSm1sH12A50nwSjGFdWnnsZ1Yg.ymcIl5Kb2UNGblYgU5gVj_Ck1cxgr4zTknzq-OXCd7cg.PNG/aFVKechPsqKQccQwFXtM.png",
      career: null,
    },
    {
      nickname: "DnDn",
      team: "농심 레드포스",
      name: "박근우",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MjBfMTEy/MDAxNjg5ODUwMzQxMjYw.Mr2Bq1LGyZ0Qi7RSKOkqLaYbVEnqK9WCa6nGqrVjaxQg.AKLVV07oH06KturunYhzDwVZ7FktOTKTEDu38YTD_gMg.PNG/UCxgXfQabJuFDlvMSIgM.png",
      career: null,
    },
    {
      nickname: "Morgan",
      team: "OK저축은행 브리온",
      name: "박루한",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMyAg/MDAxNjg4NjI2MTAwNTA2.ZLKYGudxhnp_GT_oTofWgtyezmgipfDVfW3AzMMnDPog.iAxTJr0dFUOUQTA34D_6sPlyPyyENPfZ_JhN8capn-Ug.PNG/AemcEYsVmcCxmOSvEXdL.png",
      career: null,
    },
    {
      nickname: "Kingen",
      team: "한화생명 e스포츠",
      name: "황성훈",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjcy/MDAxNjg4NjI2ODgzNjQw.Rb2ehxofhFd8Q2iRBFdHESPV_c3dF5KlOSepG_mZ_38g.PzMhhUTRURDblxv0kdwiN2L3tiMrB4Nu1nApuHWx_Kkg.PNG/elEdCvYCajrrjybQnQYJ.png",
      career: ["2018 LCK Summer 우승", "2022 Worlds 우승"],
    },
    {
      nickname: "PerfecT",
      team: "KT 롤스터",
      name: "이승민",
      img: "https://nng-phinf.pstatic.net/MjAyMzEwMDlfNTYg/MDAxNjk2ODI3ODYwNzU0.0JDX3qNhLWQBf_XdW5DKrstNalf0NucajcWhqps2teUg.ALahJyTVP06AVTHTVtgt846EeeA3hUe2-xNS_Ncoo1Qg.PNG/BiGfdOWAqVUlEYhuLYDo.png",
      career: null,
    },
    {
      nickname: "Clear",
      team: "리브 샌드박스",
      name: "송현민",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDhfMTkz/MDAxNjg4ODA0OTAxMDM4.ZnYjS-JDA-mIULbGoV6VHChSDSIa7A7wO_4ZYitOgtQg.2SzzOXRHA0aYkcIBSDWbAgTxjqN4pOnRoLt1QSwLTjAg.PNG/UewuQeQeKHlJslOvIexE.png",
      career: null,
    },
  ],
  jgl: [
    {
      nickname: "Peanut",
      team: "Gen.G",
      name: "한왕호",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjM0/MDAxNjg4NjI2NzAxOTc2.0EQLbRt3fkKYNzVlqctFShBw0bXmAu_-Z69QPZUpuecg.VHPnzDcRLqtPOgtEGyHjHisFJMl3mvBARMaSHulB8LEg.PNG/LpQXdkAifwAvdNQEEICN.png",
      career: [
        "2016 LCK Spring 준우승",
        "2016 LCK Summer 우승",
        "2017 LCK Spring 우승",
        "2017 MSI 우승",
        "2017 LCK Summer 준우승",
        "2017 Worlds 준우승",
        "2018 LCK Spring 우승",
        "2017 MSI 준우승",
        "2018 자카르타 팔렘방 아시안 게임 은메달",
        "2022 LCK Spring 준우승",
        "2022 LCK Summer 우승",
        "2023 LCK Spring 우승",
        "2023 LCK Summer 우승",
      ],
    },
    {
      nickname: "Oner",
      team: "T1",
      name: "문현준",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNzgg/MDAxNjg4NjI3OTAyMjY1.NV4co5Y4FgjggxX4BWzFwzfHCH6zpoKgXvTK1ip0gIYg.D943q-vQWuH079BKXGosJc-3duk573Pec5KYd8Qk1dsg.PNG/PGsCstmsUqSaDqKqBjsj.png",
      career: [
        "2021 LCK Summer 준우승",
        "2022 LCK Spring 우승",
        "2022 MSI 준우승",
        "2022 LCK Summer 준우승",
        "2022 Worlds 준우승",
        "2023 LCK Spring 준우승",
        "2023 LCK Summer 준우승",
        "2023 Worlds 우승",
      ],
    },
    {
      nickname: "Willer",
      team: "리브 샌드박스",
      name: "김정현",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjcw/MDAxNjg4NjI3NTQzMDUx.kyo698ZBeorC0OqO5bx-OwrF4dL_A9jqEYrR6HDPTwAg.PYQYF7-JkOKPUX7EIGYumg-3nmSXNbZB7YYS_0gFm4Ig.PNG/NxvSPKLBvpcJWTEPOcRr.png",
      career: null,
    },
    {
      name: "김건부",
      nickname: "Canyon",
      team: "Dplus KIA",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjc4/MDAxNjg4NjI2MjgyMDkx.JgZQYZlKaJuI_j6eyeWCyVhSJa-Ltd742kM-RwIDcHkg._7CWHJzTtIrAlGKgr0GEBwv5hK5vzj1kSOaiS70mESQg.PNG/RXAhcwAxIWaHFbGgOZOw.png",
      career: [
        "2020 LCK Summer 우승",
        "2020 Worlds 우승",
        "2021 LCK Spring 우승",
        "2021 MSI 준우승",
        "2021 LCK Summer 우승",
        "2021 Worlds 준우승",
      ],
    },
    {
      nickname: "Cuzz",
      name: "문우찬",
      team: "KT 롤스터",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTAy/MDAxNjg4NjI3NDI0MjI1.l2UwoZwGheAcAtOfA8h7rsrq7DfO2BraW5c55zpqkRkg.JIZy9ZJu5C9N52Kls1hqUg4fa6kwntwTYAK-OCRDW1Yg.PNG/JScZhedStXTjSsMmaRWT.png",
      career: [
        "2017 LCK Summer 우승",
        "2018 LCK Spring 우승",
        "2018 MSI 준우승",
        "2020 LCK Spring 우승",
        "2021 LCK Summer 준우승",
      ],
    },
    {
      nickname: "Croco",
      name: "김동범",
      team: "DRX",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjY5/MDAxNjg4NjI2NTIwODI5.5fE5xyAYAfDJGfMF15xAepjUYdIvzT6psvNhgJcgaLYg.t3jxKkC_9fKhKqmIaUlPWnR73fEShav18BfkVG6VCxgg.PNG/cbmFIkcgNQXFhRxpBIOj.png",
      career: null,
    },
    {
      nickname: "YoungJae",
      team: "광동 프릭스",
      name: "고영재",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNjkg/MDAxNjg4NjI3MTgzOTE4.kT0Z1ITGThCRhTrD_1pZB8ifk3yScT2yH-vZfXgc-9kg.LOeU-C6rqDRT9m59g7rQDZt_6oOwCL6ZHM833w3vhpUg.PNG/REAinRpcdQoZgbhPLBWm.png",
      career: null,
    },
    {
      nickname: "Sylvie",
      team: "농심 레드포스",
      name: "이승복",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNSAg/MDAxNjg4NjI3NzgzOTA1.QsCOoG8zyhoAE74ZM2MoChC0to_IIHsG5izO4vb_QZwg.ee8EVZPfbI31ayWxrV-j_jE2_Mh4ozyz2QH8ri5WRmYg.PNG/ltevJodFSUIeWTqLHxlC.png",
      career: null,
    },
    {
      nickname: "UmTi",
      team: "OK저축은행 브리온",
      name: "엄성현",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjg4/MDAxNjg4NjI1OTgzMjEy.fFo4Qd3gHXLRICKG4w0IrOdMTOBWxjiSFYcz8kDtbhkg.sKrTw5NLxCQ31j1nFP4fbI3ojY1OgE_iKziq1Yh7RLAg.PNG/rhDbhhbOCKgLSaYvctik.png",
      career: null,
    },
    {
      nickname: "Grizzly",
      team: "한화생명 e스포츠",
      name: "조승훈",
      img: "https://nng-phinf.pstatic.net/MjAyMzA2MjhfMTEz/MDAxNjg3OTM2ODI1MDU1.m8QgNOzkrx-tsPaWanziQ-WYgUd9X_vKDjpjhOma9zkg.VdcC03xlD7MRNw_22y55xZmYOe0tcDdKw4m9Ft1Nt2sg.PNG/VRoIXgqrkdmFHcnyEKUc.png",
      career: null,
    },
    {
      nickname: "Juhan",
      name: "이주한",
      team: "DRX",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjM0/MDAxNjg4NjI2NTIxMDQ1.VxFvWX4tDAVYZKUnR-TMp-sNgxyi-CANBx3saG-JlaUg.q0jhrxduJGYlzPYWT1Oeyp98OKIAwqA01HLuGSLkpZ8g.PNG/UrgGLjgqupoHJzUHEfgu.png",
      career: ["2022 Worlds 우승"],
    },
  ],
  mid: [
    {
      nickname: "Chovy",
      team: "Gen.G",
      name: "정지훈",
      img: "https://nng-phinf.pstatic.net/MjAyMzA5MTJfMjU5/MDAxNjk0NDk1OTAyMDg2.I3pk7iAV1VKXSB8Ff1p2wL7fU8WDjmz2pF91oc6-oJYg.BoPps967Yp4BGCY_7vcnDCBq4BRmdIKLoe6HWApcDcMg.PNG/pdjSFwSEtFgMKMPSNwSk.png",
      career: [
        "2018 LCK Summer 준우승",
        "2019 LCK Spring 준우승",
        "2019 LCK Summer 준우승",
        "2020 LCK Summer 준우승",
        "2022 LCK Spring 준우승",
        "2022 LCK Summer 우승",
        "2023 LCK Spring 우승",
        "2023 LCK Summer 우승",
        "2022 항저우 아시안 게임 금메달",
      ],
    },
    {
      nickname: "Faker",
      team: "T1",
      name: "이상혁",
      img: "https://nng-phinf.pstatic.net/MjAyMzA5MTJfMzAw/MDAxNjk0NDk1OTAxNjUz.6EuCErf8L5Aivu_KhCPlseZodKe8gQcKTYeLNGn36wEg.YUMZ2itQzzguv-M1oN-YocXz6uG3syCEhJTbA_ZEL9sg.PNG/gXrqiGOJgAnmyuGnuTHU.png",
      career: [
        "2013 Worlds 우승",
        "2015 Worlds 우승",
        "2016 Worlds 우승",
        "2017 Worlds 준우승",
        "2022 Worlds 준우승",
        "2023 Worlds 우승",
        "2015 MSI 준우승",
        "2016 MSI 우승",
        "2017 MSI 우승",
        "2022 MSI 준우승",
        "2013 LCK Summer 우승",
        "2013 LCK Winter 우승",
        "2015 LCK Spring 우승",
        "2015 LCK Summer 우승",
        "2016 LCK Spring 우승",
        "2017 LCK Spring 우승",
        "2017 LCK Summer 준우승",
        "2019 LCK Spring 우승",
        "2019 LCK Summer 우승",
        "2020 LCK Spring 우승",
        "2021 LCK Summer 준우승",
        "2022 LCK Spring 우승",
        "2022 LCK Summer 준우승",
        "2023 LCK Spring 준우승",
        "2023 LCK Summer 준우승",
        "2018 자카르타 팔렘방 아시안 게임 은메달",
        "2022 항저우 아시안 게임 금메달",
      ],
    },
    {
      nickname: "Clozer",
      team: "리브 샌드박스",
      name: "이주현",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTg2/MDAxNjg4NjI3NTQyNjA3.3sq9MK2CoQJjyIc7kdl5BwvfTqedTHXFg4_fH_FHHYog.qmdTvyzfigYiLRgO0ClW9IAh-Ui-MlWCtEnhMqOzyUEg.PNG/jpqHdpJlJXbpXtSZzGFu.png",
      career: null,
    },
    {
      name: "허수",
      nickname: "ShowMaker",
      team: "Dplus KIA",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNjkg/MDAxNjg4NjI2MjgxODY2.BoeCECtrPFWDo6ThpeQzO3PzgV2qibpdiU1iSEKNdLcg.juPAc58Q5TkQf_zADiblv6dEvqIYJA-diIhXkSsv_sgg.PNG/ESNbuesnzTdvAEXklQcZ.png",
      career: [
        "2018 LCK Summer 우승",
        "2020 LCK Summer 우승",
        "2020 Worlds 우승",
        "2021 LCK Spring 우승",
        "2021 MSI 준우승",
        "2021 LCK Summer 우승",
        "2021 Worlds 준우승",
      ],
    },
    {
      nickname: "Bdd",
      name: "곽보성",
      team: "KT 롤스터",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNjYg/MDAxNjg4NjI3NDIzNTM1.O4NR_DOVfgTmrPzRyVHMs3F2nQVnfvbuPAC1c3Qbwyog.aJ6_wTBpOm8wSOiOpfl29a1OUlfz5JM9Ss-9CKf6CAIg.PNG/SmtigQzkZARtxtEyELqv.png",
      career: [
        "2017 LCK Summer 준우승",
        "2018 LCK Spring 준우승",
        "2018 MSI 준우승",
        "2020 LCK Spring 준우승",
        "2021 LCK Spring 준우승",
      ],
    },
    {
      nickname: "Fate",
      name: "유수혁",
      team: "DRX",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjA0/MDAxNjg4NjI2NTIwNjU4.GdJNcqhph9iWhZERNfBwLJLkd0are_SWzol2YsuAlXgg.1G667dU2OPcbU5oROwZ8RGnljiEMxfsIN2OakqJ8vzYg.PNG/CedChAZMzUksWanABPKK.png",
      career: null,
    },
    {
      nickname: "Bulldog",
      team: "광동 프릭스",
      name: "이태영",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNzMg/MDAxNjg4NjI3MTg0MDYx.AKj10Oe4jx1us43eKn59QQrlbtSwgJjEH017De02uLYg.p4MrWxGdx19HT-qW8XWcMOWNShNAghoXII_03wpCVEwg.PNG/UsJHwkNxOKjTYWIDBSnZ.png",
      career: null,
    },
    {
      nickname: "Fiesta",
      team: "농심 레드포스",
      name: "안현서",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTM5/MDAxNjg4NjI3Nzg0MDI2.PE2VocRptLcIisQV2JFcus6uMwe0Ttf3xhg4w1f0Lnkg.uEiCVK3EC4I6W3_scD0WYtTU4vVEDs47A98nUsTG-78g.PNG/OSblyqXBBbpfRKDxrKtK.png",
      career: null,
    },
    {
      nickname: "Karis",
      team: "OK저축은행 브리온",
      name: "김홍조",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjk2/MDAxNjg4NjI2MTAxMDY0.EtBAoyvf1ReM27v972Awp2tYUzblH4M0SVxROvcpDkkg.4rptOe_oEVGWyWEq1rKGRBMKlRKMbhPCTPj9lQIXJhQg.PNG/TcDKavblnkzXnIKdpmZz.png",
      career: null,
    },
    {
      nickname: "Zeka",
      team: "한화생명 e스포츠",
      name: "김건우",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNiAg/MDAxNjg4NjI2OTQxNzg3.NO_J7PQ1mA-bpLqiv0Npu35QphljeUTsMPJVvgVVb-wg.RkEru7_VXYLFGYVzmcAIcckIzJuUAz1X8Kar5tgSEkcg.PNG/JCZqkVvxbkADSfemqfjo.png",
      career: ["2022 Worlds 우승"],
    },
    {
      nickname: "Sky",
      team: "T1",
      name: "김하늘",
      img: "https://nng-phinf.pstatic.net/MjAyMzA1MjVfNzIg/MDAxNjg1MDA0MzIwMzQ1.DKoMsIy2vmo_xut658TeEp49Gst2AUuyqgs3jeFcoOEg.Z0HAt0J6JtUl8sva86nyd6ssKDLyYwq2CLNcbkTvskgg.PNG/RznuclZJKsfawhNewaIZ.png",
      career: [
        "2017 LCK Spring 우승",
        "2017 LCK Summer 준우승",
        "2023 LCK Spring 우승",
        "2023 LCK Summer 준우승",

        "2023 Worlds 우승",
      ],
    },
    {
      nickname: "kyeahoo",
      name: "강예후",
      team: "DRX",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNDQg/MDAxNjg4NjI2NTg1MzMw.QFgZ-WSSVnYYch9n29jhPGKTDyG8vuBB1Cd_An3p2pYg.zh1iVfE7j4WmxoQxcQ4T4Kgz5jyG0ZCSO65M770c6cIg.PNG/FPWWdmJcUnkaXUiGtqJY.png",
      career: null,
    },
    {
      nickname: "Quad",
      team: "농심 레드포스",
      name: "송수현",
      img: "https://nng-phinf.pstatic.net/MjAyMzExMjBfMjgw/MDAxNzAwNDUzNzgyNzY5.u_FM6kUn8qdGKbbNFuesnIr4gmBsYPw93dfNrGogyY8g.TzA5WZTxXow3Omse1HsfDurJ7aQmUasUcIaQ7agr6Hkg.PNG/NkJjkcvVXdBHrLXLGOFv.png",
      career: ["2020 LCK Summer 준우승"],
    },
    {
      nickname: "Callme",
      team: "농심 레드포스",
      name: "오지훈",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDdfMTQz/MDAxNjg4NzA0NTIxODE2.r0jhqKCLb_wDOV0GBjCAyayTPHpcfKgseA1kSxvs9K0g.qKGCfhm0UPn325tUskKFEE_m6naiqVM2LeOkSzcEKNMg.PNG/FDVSjODXyaFJvLZSaslj.png",
      career: null,
    },
  ],
  ad: [
    {
      nickname: "Peyz",
      team: "Gen.G",
      name: "김수환",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfODUg/MDAxNjg4NjI2NzAyMzY1.XmNiFz3E8Uw0GTXH0DkNXjTn5A-46-gW50DjLU1OZCEg.nxXvEzt_xdYF_iqivarZ0sDlPZeWDLfke06BSscnXScg.PNG/HUlabcQzATblGRFRdjNn.png",
      career: ["2023 LCK Spring 우승", "2023 LCK Summer 우승"],
    },
    {
      nickname: "Gumayusi",
      team: "T1",
      name: "이민형",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTQ5/MDAxNjg4NjI3OTAxODAw.4R26_85nhfHh6mRAQE_Rpz0gVEAbL7bE7N5DcmnkdGYg.Eavo-ibB2RjjDim3DMWMXUQaM-05TPcEyypyJR_aBQgg.PNG/tqFJNzRLwkUkHvHOcIrP.png",
      career: [
        "2020 LCK Spring 우승",
        "2021 LCK Summer 준우승",
        "2022 LCK Spring 우승",
        "2022 MSI 준우승",
        "2022 LCK Summer 준우승",
        "2022 Worlds 준우승",
        "2023 LCK Spring 준우승",
        "2023 LCK Summer 준우승",
        "2023 Worlds 우승",
      ],
    },
    {
      nickname: "Teddy",
      team: "리브 샌드박스",
      name: "박진성",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNjEg/MDAxNjg4NjI3NTQyMDg1.MeV3ofplLe0ax2_5LoZn0Zz9pDBmO90q-PE9RPcDfdMg.e3YNxjbjluz3_aQDK3EVaiCqfJtoVkGSrU_dpk7bPwog.PNG/YeKkZnSavYhYBsbmWjsg.png",
      career: [
        "2019 LCK Spring 우승",
        "2019 LCK Summer 우승",
        "2020 LCK Spring 우승",
        "2021 LCK Summer 준우승",
      ],
    },
    {
      name: "김혁규",
      nickname: "Deft",
      team: "Dplus KIA",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjE5/MDAxNjg4NjI2MjgxMzU5.LU3A1PCn1dcdHSjQ37b-CCoz3gB_clwhC2k0fPk3gjcg.g9tu2_6ztHBJJUOx8kM015NgQqmohlM8I8jy-MQrwjwg.PNG/LiKaKksCGlQzWtVZDRwF.png",
      career: [
        "2014 LCK Summer 준우승",
        "2015 LPL Spring 우승",
        "2015 MSI 우승",
        "2016 LPL Spring 준우승",
        "2016 LPL Summer 우승",
        "2017 LCK Spring 준우승",
        "2018 LCK Summer 우승",
        "2020 LCK Summer 준우승",
        "2022 Worlds 우승",
      ],
    },
    {
      nickname: "Aiming",
      name: "김하람",
      team: "KT 롤스터",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfODYg/MDAxNjg4NjI3NDI0NTU1.6L-zbydHCWVyd7IUrpg_m6SQRNFMeabcl1mSsj5gVwsg.loEZVFLwwf9_VjGUJxR3EWbnJV0HlEW1W6-Go2_QCEIg.PNG/dQuXNdnXAssyRxatoXjD.png",
      career: null,
    },
    {
      nickname: "Paduck",
      name: "강예후",
      team: "DRX",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTc0/MDAxNjg4NjI2NTIxMTk1.0L1GQQd9EgEkiz8IjAIxGcypGrUpv_Jw7Dcb88i_eXsg.ZvnASB6FL7BzNHE1HD6Tcn3PWXfDwQV_JQUE3RcnBiAg.PNG/ANgiWOtLMcEvxntUpBEP.png",
      career: null,
    },
    {
      nickname: "Taeyoon",
      team: "광동 프릭스",
      name: "김태윤",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTg0/MDAxNjg4NjI3MzAxOTg4.pF1NBKSOZq7Q5Kg-yCRwcGMer_cvOpIp5loXxt4OXLQg.TePjDCV4_9H2sV1PG3mD45wQsC3lzLDWoLFEP1EIAzMg.PNG/UulMlUmhzvncQjUdsxUM.png",
      career: null,
    },
    {
      nickname: "Jiwoo",
      team: "농심 레드포스",
      name: "정지우",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDdfNTIg/MDAxNjg4NzA0NTIwODQw.oZ0C7mo26zksWrCDLB2QhW3Lf2f9645K_YMw8yyYjK4g.n-L1TqIOPuWoQzVkgQYsAXX4oLuCKOWM1j3PcKgKZY4g.PNG/HQvVmLEIAfwSZvsreAJx.png",
      career: null,
    },
    {
      nickname: "Hena",
      team: "OK저축은행 브리온",
      name: "박증환",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDdfMTg1/MDAxNjg4Njk0NzQwNDc1.EZ63TsaBhpfzXPGszO-B79IciBM9bBBOMwrNJrFbZYgg.r5frdLLsoDXE5r3CbljeRbBAwzbYTncUyc9R_Jy6RCAg.PNG/QUNCZXnofxzHtTCUPBch.png",
      career: null,
    },
    {
      nickname: "Viper",
      team: "한화생명 e스포츠",
      name: "박도현",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjc2/MDAxNjg4NjI2ODgzMjQw.4Ob59OesRDTDhfW3eqkWXhSev-mrXVL1iWqIqGdpT50g.WgtAo66XjNjN5TDzhZWM3KJ0ejFwYrOHHZLpeWZTb9cg.PNG/hqjAhhuOUsBmjasYzCKy.png",
      career: [
        "2018 LCK Spring 우승",
        "2018 LCK Summer 준우승",
        "2019 LCK Spring 준우승",
        "2019 LCK Summer 준우승",
        "2020 LPL Summer 우승",
        "2021 Worlds 우승",
      ],
    },
    {
      nickname: "Deokdam",
      name: "서대길",
      team: "DRX",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTkw/MDAxNjg4NjE2NzQyNTkz.MAkdO2rYyyITLAwk8903GIUf6oMVRWeWHDAAdjOfD9Ug.8Carzr6vOSFCGWvq6NPzp-ThAiz6xduVCVxSsNz7Go0g.PNG/KwFHjypwcQmutPkoDTIc.png",
      career: null,
    },
    {
      nickname: "Pleata",
      name: "손민우",
      team: "DRX",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MTBfMTYz/MDAxNjg4OTc3NTg3MjY4.0ajhQlxJbmoA6okuGUtgGo-T43ptodq71BkRhN-NyHwg.0G6jQlNpdymCPoDRTnX4OYrg5gjGhCysI60lUdx6vS4g.PNG/oYtAJvtWdFvvipZlTBSz.png",
      career: null,
    },
    {
      nickname: "Vital",
      team: "농심 레드포스",
      name: "하인성",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNzAg/MDAxNjg4NjI3Nzg0Mjgx.xrUgzG0ZRYg4NqgPeUQ5Zh109_vB00qmjFFQqSb6CLQg.UuGSljjZbZu3nbdKfLpAfzCObXiGJEUhJWqu74HuQjgg.PNG/GrVgThejeKoKenBFXHYi.png",
      career: null,
    },
    {
      nickname: "Envyy",
      team: "리브 샌드박스",
      name: "이명준",
      img: "https://nng-phinf.pstatic.net/MjAyMzA1MjVfMjUz/MDAxNjg0OTkwNzAxMTAy.926BY08zcO17raZQMx4D-Zb0csSh0kIDJuOTnN1rE6sg.6F-hhTuXOeg1PAevU6sEou1gp-d1rHuqHUiKk0ri_7Eg.PNG/pnxjnlgzCKXMuZWsxlJC.png",
      career: null,
    },
  ],
  spt: [
    {
      nickname: "Delight",
      team: "Gen.G",
      name: "유환중",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTk2/MDAxNjg4NjI2NzAyMjM2.5YsKPhIqcp6lTAdafm7Qo2LIgGgaDbthjPaQfT0CCaQg.P5Cls70UFR3UHBWgPsk15Px1KucvHJDd9yL1lqqREMog.PNG/DXASSvCWFKuNJAAmYGwd.png",
      career: ["2023 LCK Spring 우승", "2023 LCK Summer 우승"],
    },
    {
      nickname: "Keria",
      team: "T1",
      name: "류민석",
      img: "https://nng-phinf.pstatic.net/MjAyMzA5MTJfMjYz/MDAxNjk0NDk2MDIyODAy.U0124KDUBZG5pcIZvhkrnGZb1g4z-6dGEfhu1PZPxrog.-ebhr0BHM3T2Vp3q1ED1V4DJvjBf_y9llld4HRoqIhsg.PNG/RjRBpHNOORsmoouTTRtp.png",
      career: [
        "2020 LCK Summer 준우승",
        "2021 LCK Summer 준우승",
        "2022 LCK Spring 우승",
        "2022 MSI 준우승",
        "2022 LCK Summer 준우승",
        "2022 Worlds 준우승",
        "2023 LCK Spring 준우승",
        "2023 LCK Summer 준우승",
        "2022 항저우 아시안 게임 금메달",
        "2023 Worlds 우승",
      ],
    },
    {
      nickname: "Kael",
      team: "리브 샌드박스",
      name: "김진홍",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTEx/MDAxNjg4NjI3NTQyODg2.O5zPc_XhdpmLZkjQrzhe-l0YjIgAUoCh97RBigBM8eQg.MGdSkpJE1KFFknjlv-lIzi1XhlsHy-3ZcEsF6e_JDC8g.PNG/BUWBFGbiomYXVrXMPDmS.png",
      career: null,
    },
    {
      name: "김형규",
      nickname: "Kellin",
      team: "Dplus KIA",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MjhfMTYz/MDAxNjkwNTMxMTYxODEx.6FQqHY3LXv6X2BfHgtQenZAwT9BDDTyXqDaE8BCkze4g.CdZuRXIfp_JSWfLhBXwbvzy4c9sPm6ryo6F0uxBHA44g.PNG/GdOeNXQWOESCWyitozEU.png",
      career: ["2020 LCK Spring 준우승"],
    },
    {
      nickname: "Lehends",
      name: "손시우",
      team: "KT 롤스터",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjA1/MDAxNjg4NjI3NDI0MDcy.jcZS7whHzycRYqjcOjPAek1SOjdmdIZU5iAfzvAdPSYg.ABFcnMgZ-jcjmqjoo5XFAnhMBN5qno1gPo7WiJez6Xog.PNG/gDXhalcICcdGUeMcqcPD.png",
      career: [
        "2018 LCK Summer 준우승",
        "2019 LCK Spring 준우승",
        "2019 LCK Summer 준우승",
        "2022 LCK Spring 준우승",
        "2022 LCK Summer 우승",
      ],
    },
    {
      nickname: "BeryL",
      name: "조건희",
      team: "DRX",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTAy/MDAxNjg4NjI2NTIwNDk3.h89wLhpZobkjUP7cYavwefe6-fD0wAMQg6rbbdKfXQ8g.5NSp2C6XSFRsqhHiryF7vrSn1NJpmBVBTTYtWCVpiXQg.PNG/dihOEhbTyHFTLQMYFiWk.png",
      career: [
        "2020 LCK Summer 우승",
        "2020 Worlds 우승",
        "2021 LCK Spring 우승",
        "2021 MSI 준우승",
        "2021 LCK Summer 우승",
        "2021 Worlds 준우승",
        "2022 Worlds 우승",
      ],
    },
    {
      nickname: "Jun",
      team: "광동 프릭스",
      name: "윤세준",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfNjkg/MDAxNjg4NjI3MTgzOTE4.kT0Z1ITGThCRhTrD_1pZB8ifk3yScT2yH-vZfXgc-9kg.LOeU-C6rqDRT9m59g7rQDZt_6oOwCL6ZHM833w3vhpUg.PNG/REAinRpcdQoZgbhPLBWm.png",
      career: null,
    },
    {
      nickname: "Peter",
      team: "농심 레드포스",
      name: "정윤수",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMjI4/MDAxNjg4NjI3Nzg0MTIy.KE1uNehdH-YU1mpVEufg5AUruDJe3eo4ryCza58djWYg.vuLkwclGbTNyGowPEMelaXvixEWWANlEbSWulGsQa7wg.PNG/zNgOYNBMfTrjrwQUPhLJ.png",
      career: null,
    },
    {
      nickname: "Effort",
      team: "OK저축은행 브리온",
      name: "이상호",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTA3/MDAxNjg4NjI1OTgzNzQy.TBHp69eynJ7GgPlFh0J9fkz_q7r36aVXB9e2xOlJjOwg.raQFzuPtZDxMRnsOmfTOZi9N9hwAeYHNCgo3MwfyQ9Ag.PNG/ewEebpNfimQuLMrihYUt.png",
      career: [
        "2019 LCK Spring 우승",
        "2019 LCK Summer 우승",
        "2020 LCK Spring 우승",
      ],
    },
    {
      nickname: "Life",
      team: "한화생명 e스포츠",
      name: "김정민",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDZfMTAy/MDAxNjg4NjI2ODgzNDUy.PlhmyoEEgppJACBqOIsTlJyxBRlpIRgaSWL1zdto6KMg.POgG4_i-jO23hDIcxIk_s3ftVtaxEccPNQTOnkVMEc4g.PNG/lboQwgbUEGPCvsjTCuAY.png",
      career: ["2020 LCK Spring 준우승", "2021 LCK Spring 준우승"],
    },
    {
      name: "윤설",
      nickname: "Bible",
      team: "Dplus KIA",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MjhfMjIg/MDAxNjkwNTMxNDYwNzUy.f5zv6SCex3xZrtatFwVhRPXh7J6G68Ce1-a8XA7MkV8g.VsRmpiJ9bmMCFenHVrmbrKn5lW-oDSKv-33iP4Mh1p8g.PNG/LUNyYQVIMgEROuuIKdJi.png",
      career: null,
    },
    {
      nickname: "Andil",
      team: "광동 프릭스",
      name: "문관빈",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDlfMTkw/MDAxNjg4ODg4NjAwOTI5.8VFcl9z3-3OpDBHRVuvuDMKNPeGvbNHz-f8em6XhSlog.zbXS_uJxQS_rPoPTiGxAqtUQayYd64O5Fa4l6kLZiiIg.PNG/POrqUpKXMgATsjuqzWms.png",
      career: null,
    },
    {
      nickname: "Moham",
      team: "광동 프릭스",
      name: "정재훈",
      img: "https://nng-phinf.pstatic.net/MjAyMzA3MDdfMjcx/MDAxNjg4NzA2MjAwNTQ2.btcz_I9WUh73XJYH5OGRuztWMkCxB08_xLmC-FC1xEcg.qNazYSk6oerbYDjBg2i0iCg6XWBdY2o_epKitDtrXWog.PNG/PJyGmWxKDFoJUadjrwAP.png",
      career: null,
    },
  ],
}
